config/routes.rb
Rails.application.routes.draw do



  root 'main_static_pages#home'
  
  #main static pages controller routes
  get 'about' => 'main_static_pages#about'
  get 'contact' => 'main_static_pages#contact'
  get 'home' => 'main_static_pages#home'
  get 'contact' => 'main_static_pages#contact'
  get 'resources' => 'main_static_pages#resources'
  
  #user controller routes
  get 'signup' => 'users#new'
  get 'editUser' => 'users#edit'
  get 'userRecipes'=> 'users#recipes'
  #user edits controller routes
  get 'addProfileContent' =>'user_edits#add'
  get 'manageProfileContent' =>'user_edits#home'

  #recipes
  get 'allRecipes' => 'recipes#index'


  #following three  routes below may not be used 

    #user interests bridge
    get 'addNewInterest' => 'interests#new'
    get 'addInterest' => 'user_interests#new'
    
    #user activity
    get 'addNewActivity' => 'activities#new'   
    get 'addActivity' => 'user_activities#new'
    
    #user sport
    get 'addNewSport' => 'sports#new'
    get 'addSport' => 'user_sports#new'

    #user movie
    get 'addNewMovie' => 'movies#new'
    get 'addMovie' => 'user_movies#new'

    #user movie
    get 'addNewBook' => 'books#new'
    get 'addBook' => 'user_books#new'

    #user book
    get 'addNewTvshow' => 'tvshows#new'
    get 'addTvshow' => 'user_tvshows#new'



  #session controller routes....login sends a GET and POST request 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'#post command 'sends all form submition data' to the user
  delete 'logout'  => 'sessions#destroy'

  #user following association
  resources :users do
    member do
      get :following, :followers
    end
  end


  #resources utilized ith user model. This must include the users_helper helper files 
  resources :users, :interests, :activities, :sports, :movies, :books, :tvshows,
  :user_interests, :user_activities, :user_sports, :user_movies, :user_books, :user_tvshows

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :recipes

end


#provides GET(aquire) POST() DELETE HTTP commands which are used in hyperlinks. Imagine this as a template file 
#to all of the resources links i want use for navigation and utilization for the user. 

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user

	has_many :ingredients
	has_many :directions

  	mount_uploader :picture, RecipeUploader

	accepts_nested_attributes_for :ingredients,
									reject_if: proc { |attributes| attributes['name'].blank? },
									allow_destroy: true
 	accepts_nested_attributes_for :directions,
									reject_if: proc { |attributes| attributes['name'].blank? },
									allow_destroy: true

    validates :title, :description, :picture, presence: true

	#has_attached_file :image, styles: { :medium => "400#400" }
	#validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]

	def index
		@recipe = Recipe.all.order("created_at DESC")
		
	end

	def show
		@user = User.find(@recipe.user.id)

	end

	def new
		if logged_in?
			@recipe = current_user.recipes.build
		else
			redirect_to login_path,  notice: "Please log in to add recipes or create a new profile"
		end

	end

	def create
		@recipe = current_user.recipes.build(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Successfully created new recipe"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to allRecipes_path, notice: "Successfully deleted recipe"
	end

	private

	def recipe_params
		params.require(:recipe).permit(:title, :description, :picture, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :name, :_destroy])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove Direction", f, class: "btn btn-default form-button"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= @recipe.errors.count
				Prevented this recipe froms saving
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :description, input_html: { class: 'form-control' }
		= f.file_field :picture, input_html: { class: 'form-control' }
		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add Direction', f, :directions, class: "btn btn-default add-button"

	= f.button :submit, class: "btn btn-primary"



<script type="text/javascript">
$('#micropost_picture').bind('change', function() {
var size_in_megabytes = this.files[0].size/1024/1024;
if (size_in_megabytes > 5) {
alert('Maximum file size is 5MB. Please choose a smaller file.');
}
});
</script>

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'	

app/views/recipes/index.haml
- @recipe.each_slice(4) do |recipes|
	.row
		- recipes.each do |recipe|
			.col-md-3
				.recipe
					.image_wrapper
						= link_to recipe do
							= image_tag recipe.picture.url
					%h2= link_to recipe.title, recipe
	.row
		.col-md-12
			- if !logged_in? 
				= link_to "Log in or create an account today!", login_path, class: "btn btn-primary btn-lg"


		

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", allRecipes_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_content
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.picture, class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p.description= @recipe.description
				%p
					Submitted by
					= @recipe.user.email
					= link_to @recipe.user.fname, @recipe.user


	.row
		.col-md-6
			#ingredients
				%h2 Ingredients
				%ul
					- @recipe.ingredients.each do |ingredient|
						%li= ingredient.name

		.col-md-6
			#directions
				%h2 Directions
				%ul
					- @recipe.directions.each do |direction|
						%li= direction.name

	.row
		.col-md-12
			= link_to "Back", allRecipes_path, class: "btn btn-default"
			- if logged_in? && @recipe.user.id == @current_user.id
				= link_to "Edit", edit_recipe_path, class: "btn btn-default"
				= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"