config/routes.rb
Rails.application.routes.draw do



  root 'main_static_pages#home'
  
  #main static pages controller routes
  get 'about' => 'main_static_pages#about'
  get 'contact' => 'main_static_pages#contact'
  get 'home' => 'main_static_pages#home'
  get 'contact' => 'main_static_pages#contact'
  get 'resources' => 'main_static_pages#resources'
  
  #user controller routes
  get 'signup' => 'users#new'
  get 'editUser' => 'users#edit'
  get 'userRecipes'=> 'users#recipes'
  #user edits controller routes
  get 'addProfileContent' =>'user_edits#add'
  get 'manageProfileContent' =>'user_edits#home'

  #recipes
  get 'allRecipes' => 'recipes#index'


  #following three  routes below may not be used 

    #user interests bridge
    get 'addNewInterest' => 'interests#new'
    get 'addInterest' => 'user_interests#new'
    
    #user activity
    get 'addNewActivity' => 'activities#new'   
    get 'addActivity' => 'user_activities#new'
    
    #user sport
    get 'addNewSport' => 'sports#new'
    get 'addSport' => 'user_sports#new'

    #user movie
    get 'addNewMovie' => 'movies#new'
    get 'addMovie' => 'user_movies#new'

    #user movie
    get 'addNewBook' => 'books#new'
    get 'addBook' => 'user_books#new'

    #user book
    get 'addNewTvshow' => 'tvshows#new'
    get 'addTvshow' => 'user_tvshows#new'



  #session controller routes....login sends a GET and POST request 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'#post command 'sends all form submition data' to the user
  delete 'logout'  => 'sessions#destroy'

  #user following association
  resources :users do
    member do
      get :following, :followers
    end
  end


  #resources utilized ith user model. This must include the users_helper helper files 
  resources :users, :interests, :activities, :sports, :movies, :books, :tvshows,
  :user_interests, :user_activities, :user_sports, :user_movies, :user_books, :user_tvshows

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :recipes

end


#provides GET(aquire) POST() DELETE HTTP commands which are used in hyperlinks. Imagine this as a template file 
#to all of the resources links i want use for navigation and utilization for the user. 

app/controllers/user_edits_controller.rb
class UserEditsController < ApplicationController
  
  
  def home
    if logged_in?
    	#method where the user will be able to see the content on their profile and get directed to the right location
    	#show all of the users current recipes, sports, interests, activities, and sofourth 
    	@user = current_user
      #gather all of the current users profile content
      @userInterestsBoard = @user.user_interests
      @userActivitiesBoard = @user.user_activities
      @userSportsBoard = @user.user_sports
      @userMoviesBoard = @user.user_movies
      @userBooksBoard = @user.user_books
      @userTvshowsBoard = @user.user_tvshows


      @userRecipes = @user.recipes
      #user information to add within the page
    else
      redirect_to root_url
    end
  end

end

app/helpers/user_edits_helper.rb
module UserEditsHelper
end

app/views/user_edits/add.html.erb
<% if logged_in? %>


	<div class="row clearfix text-center">
		<h1>Hello <%= @user.fname %> <%= @user.lname %></h1>
		<h2>This is where you get to add interests, sports, and even activities</h2>

		<div class="col-md-1 column"></div>

		<div class="col-md-3 column">
			<h2>Interests</h2>

			<p>Interest Drop Down Menu Here</p>


		</div>

		<div class="col-md-3 column">
			<h2>Activities</h2>
			<p>Activities Drop Down Menu Here</p>



		</div>

		<div class="col-md-3 column">
			<h2>Sports</h2>
			<p>Sports Drop Down Menu Here</p>




		</div>

		<div class="col-md-1 column"></div>

	</div>

	<%else%>

	<h1>Must be logged in to perform these account changes</h1>	

<% end %>

app/views/user_edits/create.html.erb
<h1>UserEdits#create</h1>
<p>Find me in app/views/user_edits/create.html.erb</p>

app/views/user_edits/edit.html.erb
<h1>UserEdits#edit</h1>
<p>Find me in app/views/user_edits/edit.html.erb</p>

app/views/user_edits/home.html.erb
<% if logged_in? %>
	<div class="row clearfix text-center">
		<h1>Hello <%= @user.fname %> <%= @user.lname %></h1>
		<h2>Here are your current sports, activities, and interests you have</h2>

		<div class="row">
			<div class="col-md-2 column"> <!-- Interest-->
				<h2>Interests</h2>

				<%=link_to 'Add Interest', addInterest_path, class:"btn btn-primary btn-block" %>

				<table class= "table table-hover table-condensed  alert alert-info">
					<tr>
						<th class="text-center">Your Interests</th>
						<th class="text-center alert alert-danger"><b>DEL</b></th>
					</tr>
					
					<% @userInterestsBoard.each do |i| %>
						<tr>
							<td class="active">
								<%= i.interest.name %>
							</td>
							<td >
								<%=
									link_to 'X', i, method: :delete, class:"btn btn-danger"
								%>
							</td>
						</tr>
					<% end %>
				</table>
			</div>

			<div class="col-md-2 column">
				<h2>Activities</h2>

				<%=link_to 'Add Activity', addActivity_path, class:"btn btn-primary btn-block" %>

				<table class= "table table-hover table-condensed  alert alert-info">
					<tr>
						<th class="text-center">Your Activities</th>
						<th class="text-center alert alert-danger"><b>DEL</b></th>

					</tr>
					
					<% @userActivitiesBoard.each do |a| %>
						<tr>
							<td class="active">
								<%= a.activity.name %>
							</td>
							<td >
								<%=
									link_to 'X', a, method: :delete, class:"btn btn-danger"
								%>
							</td>
						</tr>
					<% end %>

					
				</table>
			</div>

			<div class="col-md-2 column">
				<h2>Sports</h2>			
				<%=link_to 'Add Sport', addSport_path, class:"btn btn-primary btn-block" %>

				<table class= "table table-hover table-condensed  alert alert-info">
					<tr>
						<th class="text-center">Your Sport</th>
						<th class="text-center alert alert-danger"><b>DEL</b></th>

					</tr>

					<% @userSportsBoard.each do |s| %>
						<tr>
							<td class="active">
								<%= s.sport.name %>
							</td>
							<td >
								<%=
									link_to 'X', s, method: :delete, class:"btn btn-danger"
								%>
							</td>
						</tr>
					<% end %>

				</table>
			</div>

			<div class="col-md-2 column">
				<h2>Movies</h2>			
				<%=link_to 'Add Movie', addMovie_path, class:"btn btn-primary btn-block" %>

				<table class= "table table-hover table-condensed  alert alert-info">
					<tr>
						<th class="text-center">Your Movies</th>
						<th class="text-center alert alert-danger"><b>DEL</b></th>

					</tr>

					<% @userMoviesBoard.each do |m| %>
						<tr>
							<td class="active">
								<%= m.movie.name %>
							</td>
							<td >
								<%=
									link_to 'X', m, method: :delete, class:"btn btn-danger"
								%>
							</td>
						</tr>
					<% end %>

				</table>
			</div>

			<div class="col-md-2 column">
				<h2>Books</h2>			
				<%=link_to 'Add New Book', addBook_path, class:"btn btn-primary btn-block" %>

				<table class= "table table-hover table-condensed  alert alert-info">
					<tr>
						<th class="text-center">Your Books</th>
						<th class="text-center alert alert-danger"><b>DEL</b></th>

					</tr>

					<% @userBooksBoard.each do |b| %>
						<tr>
							<td class="active">
								<%= b.book.name %>
							</td>
							<td >
								<%=
									link_to 'X', b, method: :delete, class:"btn btn-danger" 
								%>
							</td>
						</tr>
					<% end %>

				</table>
			</div>

			<div class="col-md-2 column">
				<h2>Television Shows</h2>			
				<%=link_to 'Add New TV Show', addTvshow_path, class:"btn btn-primary btn-block" %>

				<table class= "table table-hover table-condensed  alert alert-info">
					<tr>
						<th class="text-center">Your TV shows</th>
						<th class="text-center alert alert-danger"><b>DEL</b></th>

					</tr>

					<% @userTvshowsBoard.each do |tv| %>
						<tr>
							<td class="active">
								<%= tv.tvshow.name %>
							</td>
							<td >
								<%=
									link_to 'X', tv, method: :delete, class:"btn btn-danger"
								%>
							</td>
						</tr>
					<% end %>

				</table>
			</div>

		</div>

		<div class="row">

			<div class="col-md-12 column">
				<h2>My Recipes</h2>

				<%=link_to 'Add a Recipe', new_recipe_path, class:"btn btn-primary btn-block" %>


				<table class= "table table-hover table-condensed  alert alert-info">
					<tr>
						<th class="text-center">My Recipes </th>
						<th class="text-center alert alert-danger"><b>DEL</b></th>

					</tr>

					<% @userRecipes.each do |r| %>
						<tr >
							<td class="active">
								<p><%= r.title %></p>
							</td>
							<td >
								<%=
									link_to 'X', r, method: :delete, class:"btn btn-danger"
								%>
							</td>
						</tr>
					<% end %>

				</table>
			</div>
		</div>


	</div>

	<%else%>

	<h1>Must be logged in to perform these account changes</h1>	

<% end %>

app/views/user_edits/update.html.erb
<h1>UserEdits#update</h1>
<p>Find me in app/views/user_edits/update.html.erb</p>