config/routes.rb
Rails.application.routes.draw do



  root 'main_static_pages#home'
  
  #main static pages controller routes
  get 'about' => 'main_static_pages#about'
  get 'contact' => 'main_static_pages#contact'
  get 'home' => 'main_static_pages#home'
  get 'contact' => 'main_static_pages#contact'
  get 'resources' => 'main_static_pages#resources'
  
  #user controller routes
  get 'signup' => 'users#new'
  get 'editUser' => 'users#edit'
  get 'userRecipes'=> 'users#recipes'
  #user edits controller routes
  get 'addProfileContent' =>'user_edits#add'
  get 'manageProfileContent' =>'user_edits#home'

  #recipes
  get 'allRecipes' => 'recipes#index'


  #following three  routes below may not be used 

    #user interests bridge
    get 'addNewInterest' => 'interests#new'
    get 'addInterest' => 'user_interests#new'
    
    #user activity
    get 'addNewActivity' => 'activities#new'   
    get 'addActivity' => 'user_activities#new'
    
    #user sport
    get 'addNewSport' => 'sports#new'
    get 'addSport' => 'user_sports#new'

    #user movie
    get 'addNewMovie' => 'movies#new'
    get 'addMovie' => 'user_movies#new'

    #user movie
    get 'addNewBook' => 'books#new'
    get 'addBook' => 'user_books#new'

    #user book
    get 'addNewTvshow' => 'tvshows#new'
    get 'addTvshow' => 'user_tvshows#new'



  #session controller routes....login sends a GET and POST request 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'#post command 'sends all form submition data' to the user
  delete 'logout'  => 'sessions#destroy'

  #user following association
  resources :users do
    member do
      get :following, :followers
    end
  end


  #resources utilized ith user model. This must include the users_helper helper files 
  resources :users, :interests, :activities, :sports, :movies, :books, :tvshows,
  :user_interests, :user_activities, :user_sports, :user_movies, :user_books, :user_tvshows

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :recipes

end


#provides GET(aquire) POST() DELETE HTTP commands which are used in hyperlinks. Imagine this as a template file 
#to all of the resources links i want use for navigation and utilization for the user. 

app/controllers/main_static_pages_controller.rb
class MainStaticPagesController < ApplicationController
  def home
    #home will show the parallax bootstrap effect 
    if logged_in?
      @users = User.all
      @micropost = current_user.microposts.build if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page], :per_page => 6)
      @user = User.new

    end
  end

  def recipe
    #recipe will be its own controller consisting of ViewRecipes, Edit, Delete,, 
  end

  def resources
  	
  end

  def about

  end

  def contact

  end
  
  
end

app/helpers/main_static_pages_helper.rb
module MainStaticPagesHelper
	
end

app/views/main_static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
	<h1>About</h1>

	<div class="row cleafix">
		<div class="col-md-6 col-md-offset-3">
			<h3>
				Created by Juan Luis Andujar. A Computer Science Major from Massachusetts College of Liberal Arts(MCLA)
			</h3>


		</div>	

	</div>

</div>

app/views/main_static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center jumbotron">
	<h1>Contact</h1>

	<h2>
	 Contact Page for My Sweet Spot
	</h2>

</div>

app/views/main_static_pages/home.html.erb
<% provide(:title, "Home") %>
<!-- NOTE: there is a lot of duplicate CSS information that can easily be placed into a class or ID in the custom.css file. Some of these 
	repetitive things include color, text-center, 
	 -->

	<% if logged_in? %>
		<div class="row clearfix alert alert-info" >
		
			<!-- This is grid is for the home page containing all of the users friends and information -->
			<div class="col-md-12 column" >

			<div class="row">

				<aside class="col-md-12">
				  <section class="user_info">
				    <%= render 'shared/user_info' %>
				  </section>
				  <section class="micropost_form">
				    <%= render 'shared/micropost_form' %>
				  </section>
				</aside>
			
			</div>
	
				<h3 class="text-center text-primary " >
					Follwer Updates
				</h3>	
				<div>	
					 <h3>Micropost Feed -- Current User Only for now --</h3>
	 					 <%= render 'shared/feed' %>
				</div>

			</div>

		</div>
	
	<% else %>


<div class="bg"></div>
<div class="jumbotron">
  <div class="center jumbotron">
			<h1>Welcome to Sweet Spot </h1>

			<h2>
				SweetSpot is a social network that allows people with type-1 diabetes to communicate and share their ideas. 
				This website is also meant to be a tool for people who don’t know about diabetes, people who just recently became diagnosed or even people who just feel like supporting friends or the effort for a cure. 

				SweetSpot allows you to follow other users, view status updates, customize your own profile, and also add recipes to share with other users. 
			</h2>

			<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
</div>

<div class="container">
  <div class="row">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		    <li data-target="#myCarousel" data-slide-to="1"></li>
		    <li data-target="#myCarousel" data-slide-to="2"></li>
		    <li data-target="#myCarousel" data-slide-to="3"></li>
		  </ol>

		  <!-- Wrapper for slides -->
		  <div class="carousel-inner text-center" role="listbox">
		    <div class="item active">
	     		<%= link_to image_tag("home2.png", alt: "Edit Logo"),'http://www.idf.org/', id: "logoh" %>
		    </div>

		    <div class="item">
 	     		<%= link_to image_tag("userprofile2.png", alt: "Home Logo"),'http://www.idf.org/', id: "logoh" %>
		    </div>

		    <div class="item">
   	     		<%= link_to image_tag("recipes2.png", alt: "Profile Logo"),'http://www.idf.org/', id: "logoh" %>
		    </div>

		    <div class="item">
   	     		<%= link_to image_tag("edit2.png", alt: "Recipe Logo"),'http://www.idf.org/', id: "logoh" %>		     
		    </div>
		  </div>

		  <!-- Left and right controls -->
		  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
	</div>
  <hr>
  <div class="row text-center " style="color:white;">
    <h3>Create a Profile!</h3>
	    Create a profile and add interests, sports, activities, movies, tv shows, and more to express yourself
    <h3>Add Recipes!</h3>
	    Add recipes to share with others along with learn new ones as well!
    <h3>Meet new people!</h3>
	    Make new friends and provide support to those who are in need of finding new friends
  </div>
  <hr>
  <div class="row">

	  <h3>Log in</h3>

		<div class="row " style="color:white;">
		  <div class="col-md-6 col-md-offset-3">
		    <%= form_for(:session, url: login_path) do |f| %>

		      <%= f.label :email %>
		      <%= f.text_field :email, class: 'form-control' %>

		      <%= f.label :password %>
		      <%= link_to "(forgot password)", new_password_reset_path %>
		      <%= f.password_field :password, class: 'form-control' %>

		       <%= f.label :remember_me, class: "checkbox inline" do %>
		         <%= f.check_box :remember_me %>
		         <span>Remember me on this computer</span>
		       <% end %>


		      <%= f.submit "Log in", class: "btn btn-primary" %>
		    <% end %>
		  </div>
		</div>
	</div>

	<div class="row">

	  
	</div>
</div>

		

	<% end %>
<script type="text/javascript">

var jumboHeight = $('.jumbotron').outerHeight();
function parallax(){
    var scrolled = $(window).scrollTop();
    $('.bg').css('height', (jumboHeight-scrolled) + 'px');
}

$(window).scroll(function(e){
    parallax();
});
	

</script>







	<!-- This grid below is for groups and events-->
	

app/views/main_static_pages/recipe.html.erb
<% provide(:title, "Recipes") %>
<div class="center jumbotron">
	<h1>Recipes</h1>

	<h2>
	The recipes page will contain food recipes upload by other users on the website. This page will be an effective way for users to find, and share recipe ideas. 
	</h2>

	<p><b>DISCLAIMER> This view will need its own controller object once a database model is created</b></p>

	<p><b>DISCLAIMER2> The like button equivalent on FB to recipes is Bolus(syringe needle symbol)</b></p>

</div>

app/views/main_static_pages/resources.html.erb
<% provide(:title, "Resources") %>
<div class="center jumbotron">
	<h1>Resources</h1>

	<h2>
		Websites
	</h2>

	<a class="btn btn-primary btn-lg btn-block" href="https://IDF.org">International Diabetes Federation</a>
	<a class="btn btn-primary btn-lg btn-block" href="http://en.wikipedia.org/wiki/Diabetes_mellitus_type_1">About Type 1 Diabetes</a>
	<a class="btn btn-primary btn-lg btn-block" href="http://www.diabetes.org">Diabetes.org</a>
	<a class="btn btn-primary btn-lg btn-block" href="http://ndep.nih.gov">National Diabetes Educational Program</a>
	<a class="btn btn-primary btn-lg btn-block" href="http://www.diabetescare.net">DiabetesCare.net</a>
	
</div>